Favoring clean yard over rubocop violation
I'm choosing to add a Rubocop variance instead of maintaining a
yarddoc error.

The following Rubocop violation occurred:

```console
Redundant curly braces around a hash parameter.
Contracts::String, { Contracts::KeywordArgs[identifier_builder: Contracts::Func[Cogitate::IdentifierBuilderInterface]] =>
```

If I follow rubocop's advice and tidy up the contract, I instead create a yardoc error:

```console
[error]: Unhandled exception in ContractHandler:
[error]:   in `app/repositories/cogitate/repositories/remote_netid_repository.rb`:9:

	9: Contract(Contracts::KeywordArgs[identifier: Cogitate::IdentifierInterface])

[error]: NoMethodError: undefined method `source' for false:FalseClass
```